### ISSUE TITLE
No data from Solcast: Permission Denied

### ISSUE THREAD

**Issue by stefanwest1** [BJReplay/ha-solcast-solar#92]
### The problem

I’ve added the integration through HACS in a HA Docker container. I’ve added the API and tried reloading multiple times. I’m still not getting any site data

### What version of Solcast Integration has the issue?

V.4.0.31

### What version of Home Assistant are you using?

Docker

### Diagnostics information

[config_entry-solcast_solar-01J35KSCYRR6YC1KHDYFR6RKFX.json](https://github.com/user-attachments/files/16314473/config_entry-solcast_solar-01J35KSCYRR6YC1KHDYFR6RKFX.json)

### Logs debug/info/error output

```txt
Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:192
integration: Solcast PV Forecast (documentation, issues)
First occurred: 5:06:08 PM (1 occurrences)
Last logged: 5:06:08 PM

SOLCAST - sites_data Exception error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 148, in sites_data async with aiofiles.open(apiCacheFileName, 'w') as f: File "/usr/local/lib/python3.12/site-packages/aiofiles/base.py", line 98, in __aenter__ self._obj = await self._coro ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiofiles/threadpool/__init__.py", line 94, in _open f = yield from loop.run_in_executor(executor, cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ PermissionError: [Errno 13] Permission denied: 'solcast-sites.json'
```

**Comment by autoSteve** [comment]
Solved in beta v4.0.32.

Beta v4.0.39 will release within hours.
